version: '3'
services:
  apache:
    container_name: fork_apache
    image: webdevops/apache:ubuntu-16.04
    environment:
      WEB_DOCUMENT_ROOT: /var/www/public
      WEB_ALIAS_DOMAIN: fork.localhost
      WEB_PHP_SOCKET: php-fpm:9000
    volumes: # Only shared dirs to apache (to be served)
      - ./public:/var/www/public:cached
      - ./storage:/var/www/storage:cached
    networks:
      - fork-network
    ports:
      - "8081:80"
      - "443:443"
  php-fpm:
    container_name: fork_php
    image: jguyomard/laravel-php:7.3
    volumes:
      - ./:/var/www/
      - ./ci:/var/www/ci:cached
      - ./vendor:/var/www/vendor:delegated
      - ./storage:/var/www/storage:delegated
      - ./node_modules:/var/www/node_modules:cached
      - ~/.ssh:/root/.ssh:cached
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ~/.composer/cache:/root/.composer/cache:delegated
    networks:
      - fork-network
  db:
    container_name: fork_db
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fork
      MYSQL_USER: fork
      MYSQL_PASSWORD: secret
    volumes:
      - fork-data:/var/lib/mysql
    networks:
      - fork-network
    ports:
      - "33060:3306"
networks:
  fork-network:
    driver: "bridge"
volumes:
  fork-data:
    driver: "local"
