branch-defaults:
  master:
    environment: Forkthecoop-env
environment-defaults:
  Forkthecoop-env:
    branch: null
    repository: null
global:
  application_name: ForkTheCoop
  default_ec2_keyname: null
  default_platform: PHP 7.3 running on 64bit Amazon Linux
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
